require("user.impatient")
require("user.options")
require("user.keybindings")
require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.lsp")
require("user.debugger")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
--[[ require("user.bufferline") ]]
require("user.null-ls")
require("user.lualine")
require("user.indentline")
require("user.whichkey")
require("user.autocommands")
require("user.presence")
require("user.trouble")
require("user.marks")
require("user.misc")
require("user.bracey")

-- require("user.toggleterm")
-- require("user.alpha")
-- require("user.symbols-outline")
-- require("user.truezen")
-- require("user.todo-comments")
-- require("user.venn")
-- require("user.nabla") -- equations
-- require("user.goto-preview")
