vim.g.symbols_outline = {
	show_guides = true,
	relative_width = false,
	widht = 1000,
	auto_close = false,
	show_symbol_details = false,
	symbols = {
		Text = {icon =""},
		Method = {icon="m"},
		Function = {icon=""},
		Constructor = {icon=""},
		Field = {icon=""},
		Variable = {icon=""},
		Class = {icon=""},
		Interface = {icon=""},
		Module = {icon=""},
		Property = {icon=""},
		Unit = {icon=""},
		Value = {icon=""},
		Enum = {icon=""},
		Keyword = {icon=""},
		Snippet = {icon =""},
		Color = {icon =""},
		File = {icon=""},
		Reference = {icon=""},
		Folder = {icon=""},
		EnumMember = {icon=""},
		Constant = {icon=""},
		Struct = {icon=""},
		Event = {icon=""},
		Operator = {icon=""},
		TypeParameter = {icon=""},
	},
}
