-- vim.cmd [[ "nnoremap <F5> :lua require('nabla').action()<CR>" ]]
-- vim.cmd [[ "nnoremap <leader>p :lua require("nabla").popup()<CR>"]]  -- Customize with popup({border = ...})  : `single` (default), `double`, `rounded`
